# Инженерная инфраструктура

In [ ]:
from popframe.method.engineer import InfrastructureAnalyzer

analyzer = InfrastructureAnalyzer(combined_gdf, spb_hex)
results = analyzer.get_results()
results

,score,types_in_radius,geometry
0,1,[Энергоснабжение],"POLYGON ((30.12453 60.01677, 30.14338 60.01106..."
1,1,[Энергоснабжение],"POLYGON ((30.23961 60.09269, 30.2585 60.08696,..."
2,1,[Энергоснабжение],"POLYGON ((30.40522 59.85712, 30.42398 59.85134..."
3,1,[Энергоснабжение],"POLYGON ((30.19969 59.98166, 30.21852 59.97593..."
4,1,[Энергоснабжение],"POLYGON ((30.3715 60.04029, 30.39036 60.03454,..."
...,...,...,...
611,1,[Энергоснабжение],"POLYGON ((30.3081 59.72653, 30.3268 59.72075, ..."
612,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.26976 59.689, 30.28843 59.68323, ..."
613,1,[Энергоснабжение],"POLYGON ((30.27763 60.09348, 30.29652 60.08775..."
614,1,[Энергоснабжение],"POLYGON ((30.06399 59.73999, 30.08269 59.73426..."
615,1,[Энергоснабжение],"POLYGON ((30.04687 59.8682, 30.06564 59.86248,..."

In [ ]:
results[results['score']>1]

,score,types_in_radius,geometry
75,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.1021 59.77753, 30.12082 59.7718, ..."
200,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.25131 59.70704, 30.27 59.70127, 3..."
212,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.12118 59.79631, 30.13991 59.79057..."
429,2,"[Энергоснабжение, Водоотведение]","POLYGON ((30.02734 59.81268, 30.04608 59.80696..."
527,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.13972 59.77832, 30.15844 59.77258..."
532,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.47995 59.82172, 30.49869 59.81593..."
537,2,"[Энергоснабжение, Водоотведение]","POLYGON ((30.06498 59.81349, 30.08372 59.80777..."
612,2,"[Водоснабжение, Энергоснабжение]","POLYGON ((30.26976 59.689, 30.28843 59.68323, ..."